### ISSUE TITLE
Clicking outside the text input twice sets the element's value to ''

### ISSUE THREAD

**Issue by kvnneff** [jonathanong/autocomplete#2]
This can be replicated with the demo.  Select an option and click outside the text input twice.

I think this is happening because of some of the logic between Autocomplete's `hide` method and Complement's `_onblur` method.

**Comment by jonathanong** [comment]
would you like to help maintain this? i'm probably not going to touch this for half a year at least

**Comment by kvnneff** [comment]
That's cool with me, your module is the best duo/component compatible autocomplete I've been able to find.

In my fork https://github.com/staygrimm/autocomplete/commit/fe8a0678a0b51d96b608758a8ee4525e4a0a7bbe I've simply commented out the line that resets the input value and the component works exactly as I like so far, but if you have a use-case for clearing out the value I'm sure I can rework  the logic to fulfill all our needs.

**Comment by jonathanong** [comment]
that's something that can be added manually by the end user, so id on't mind. the idea was to make it like select2 or a select box where if no valid option is selected, then clear it
